# Generated by Django 5.2.8 on 2025-11-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_thumbnail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_url',
        ),
    ]
